// src/lib/components/common/image/Image.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	export let src: string;
	export let alt: string;
	export let classes: string;
	export let width: string | null;
	export let height: string | null;
	let loaded = false;
	let thisImage: any;

	onMount(() => {
		thisImage.onload = () => {
			loaded = true;
		};
	});
</script>

{#if !width && !height}
	<img {src} {alt} class:loaded bind:this={thisImage} class={classes} />
	<!-- style:--tag="img" -->
{:else}
	<img {width} {height} {src} {alt} class:loaded bind:this={thisImage} class={classes} />
	<!-- style:--tag="img" -->
{/if}

// src/components/LazyImg/Image.tsx
import React, { useEffect, useRef, useState } from 'react'

const Image = ({ src, alt, classes, width, height }: any) => {
  const [loaded, setLoaded] = useState(false)
  const thisImage = useRef<any>(null)

  useEffect(() => {
    console.log('src = ', src)

    if (thisImage.current) {
      thisImage.current.onload = () => {
        setLoaded(true)
      }
    }
  }, [])

  return (
    <>
      {!width && !height ? (
        <img
          ref={thisImage}
          src={src}
          alt={alt}
          className={`${loaded ? 'loaded' : ''} ${classes}`}
        />
      ) : (
        <img
          ref={thisImage}
          width={width}
          height={height}
          src={src}
          alt={alt}
          className={`${loaded ? 'loaded' : ''} ${classes}`}
        />
      )}
    </>
  )
}

export default Image
